version: 2 # use CircleCI 2.0
jobs: # a collection of steps

  clamav:
    working_directory: ~/enebular-agent-heroku
    docker: # run the steps with Docker
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: cramAV test
          command: |
            sudo apt-get -y update
            sudo apt-get -y install clamav
            sudo freshclam
            sudo clamscan --infected --remove --recursive ~/enebular-agent-heroku

workflows:
  version: 2
  issue-14:
    jobs:
      - clamav
  # ev2-nodejs12:
  #   jobs:
  #     - clamav